/** @format */

export const TRIGGER_FEEDBACK = 'TRIGGER_FEEDBACK';
export const REMOVE_FEEDBACK = 'REMOVE_FEEDBACK';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';
export const SIGNOUT = 'SIGNOUT';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_FAILURE = 'PROFILE_FAILURE';
export const GET_ENTRIES = 'GET_ENTRIES';
export const ENTRIES_FAILURE = 'ENTRIES_FAILURE';
